// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------- //
// m64282fp //
// -------- //

#define m64282fp_wrap_target 12
#define m64282fp_wrap 13
#define m64282fp_pio_version 0

#define m64282fp_xck_multiplier 2

static const uint16_t m64282fp_program_instructions[] = {
    0xa842, //  0: nop                    side 2
    0xf827, //  1: set    x, 7            side 6
    0xa042, //  2: nop                    side 0
    0xf049, //  3: set    y, 9            side 4
    0x6801, //  4: out    pins, 1         side 2
    0x1884, //  5: jmp    y--, 4          side 6
    0x6801, //  6: out    pins, 1         side 2
    0xfc48, //  7: set    y, 8            side 7
    0x6c01, //  8: out    pins, 1         side 3
    0x1844, //  9: jmp    x--, 4          side 6
    0xe801, // 10: set    pins, 1         side 2
    0xb842, // 11: nop                    side 6
            //     .wrap_target
    0xe800, // 12: set    pins, 0         side 2
    0xb842, // 13: nop                    side 6
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program m64282fp_program = {
    .instructions = m64282fp_program_instructions,
    .length = 14,
    .origin = -1,
    .pio_version = m64282fp_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config m64282fp_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + m64282fp_wrap_target, offset + m64282fp_wrap);
    sm_config_set_sideset(&c, 3, false, false);
    return c;
}
#endif

